import moment from "moment";
import Head from "next/head";
import React, { useEffect, useContext } from "react";
import AppointmentDescription from "../src/components/AppointmentDescription";
import Calendar from "../src/components/Calendar";
import {
  HomeFooter,
  HomeHeader,
  HomeMain,
  HomeContainer,
} from "../styles/home.styles";
import { StateContext } from "./_app";

export default function Home() {
  const { setStateContext } = useContext(StateContext);
  useEffect(() => {
    setStateContext((prevState) => {
      return {
        ...prevState,
        dateAppointed: moment().add(1, "days").format("LLLL"),
      };
    });
  }, []);

  return (
    <HomeContainer className="Home Container">
      <Head>
        <title>Calendar Appointment app</title>
        <meta
          name="app requested by Doc Planner"
          content="Generated by Ángel Bernardo Lupiáñez"
        />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <HomeHeader className="Home Header">Calendar Appointment</HomeHeader>
      <HomeMain className="Home Main">
        <div>
          Confirm your appointment with <b>Dr. Simeon Molas</b>
        </div>
        <AppointmentDescription />
        <Calendar />
      </HomeMain>

      <HomeFooter className="Home Footer">
        <div>
          Made by <br /> Ángel Bernardo Lupiáñez
        </div>
        <div>Powered by React</div>
      </HomeFooter>
    </HomeContainer>
  );
}
